[tools]
go = "latest"
node = "lts"
pnpm = "latest"
python = "prefix:3.14"
ruby = "latest"
rust = "latest"
zig = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"

[settings]
env_shell_expand = true
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = true

[settings.npm]
package_manager = "pnpm"

[env]
RUBY_CONFIGURE_OPTS = "--with-gmp --with-jemalloc --disable-install-doc"
